#!/bin/sh

cloud_gen() {
	for dir in "$1"/*/; do
    		[ -d "$dir" ] || continue

#    case "$(basename "$dir")" in
#      pix|txt|src) continue ;; # Skip these directories
#    esac

    count=$(find "$dir" -type f -name "*.md" | wc -l)

 if [ "$count" -gt 0 ]; then
      if [ "$count" -gt 80 ]; then
        size=50
      elif [ "$count" -ge 60 ]; then
        size=40
      elif [ "$count" -ge 40 ]; then
        size=30
      elif [ "$count" -ge 20 ]; then
        size=20
      else
	size=10
      fi
      dir_name=$(basename "$dir")
      url="./$(echo "$dir" | sed 's|^./||; s|/$||; s|/|/|g')"
      echo "<a href=$url><span style=font-size:${size}px;>$dir_name</span></a>" 
fi
    cloud_gen "$dir"
done
}

# Start with the current directory
cloud_gen "."
